sudo: required
services:
  - docker

before_install:
  - docker build -t pivobier/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pivobier/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-538744167223"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRETE_KEY